# Generated by Django 2.0 on 2018-01-26 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_product', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('home', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='what are you doing now?')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='profile_pictures', width_field='width_field')),
                ('height_field', models.IntegerField(default=450)),
                ('width_field', models.IntegerField(default=350)),
                ('user', models.OneToOneField(on_delete='models.cascade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_profile',
            },
        ),
    ]
