# Generated by Django 2.0 on 2018-01-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profitos',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shares',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
