# Generated by Django 2.0 on 2018-01-27 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.TextField(max_length=255)),
                ('post_pic', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete='models.cascade', related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feed',
                'ordering': ('-date',),
                'verbose_name_plural': 'Feeds',
            },
        ),
    ]
