# Generated by Django 2.0 on 2018-01-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='ad_value',
            field=models.IntegerField(default=0),
        ),
    ]
